name: shell command

on: [push]
jobs:
  run-git-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKPLACE
          echo "${{ github.token }}""
  
      - name: checkout 
        uses: actions/checkout@v2
      
      - name: List all files after checkout
        run: | 
          pwd
          ls -a