name: Folder-Specific Workflow

on:
  push:
    branches:
      - main
    paths: 
      - 'folder1/**'
      - 'folder2/**'    

jobs:
  cd1:
    if: if: "contains(github.event.head_commit.modified, 'folder1/') || contains(github.event.head_commit.added, 'folder1/')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CD1 Job
        run: |
          echo "Running CD1 Job"
          # Add your CD1 job steps here

  cd2:
    if: if: "contains(github.event.head_commit.modified, 'folder2/') || contains(github.event.head_commit.added, 'folder2/')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run CD2 Job
        run: |
          echo "Running CD2 Job"
          # Add your CD2 job steps here